---
- hosts: all
  become: true
  connection: local

  tasks:
    - name: Remove webapp containers
      docker_container:
        name: "{{ item }}"
        state: absent
      loop:
        - webapp
        - webapp-db
      tags:
        - containers

    - name: Execute resource removal tasks
      import_tasks: tasks/resources.yml
      vars:
        sso_network_state: absent
...
