---
- hosts: all
  become: true
  connection: local

  vars:
    webapp_version: 2.1.3

  tasks:
    - name: Execute resource setup tasks
      import_tasks: tasks/resources.yml
      tags:
        - kong
        - keycloak

    - name: Execute endpoint setup tasks
      import_tasks: tasks/webapp.yml
      tags:
        - keycloak
        - endpoint

    - name: Execute kong endpoint setup tasks
      import_tasks: tasks/kong-endpoint.yml
      tags:
        - kong
        - endpoint

    - name: Execute endpoint setup tasks
      import_tasks: tasks/keycloak-endpoint.yml
      tags:
        - keycloak
        - endpoint
...
