---
- block:
    - name: Authenticate with KeyCloak
      uri:
        url: "{{ svc_auth_baseurl }}/auth/realms/{{ auth_realm }}\
          /protocol/openid-connect/token"
        method: POST
        body_format: form-urlencoded
        body:
          client_id: admin-cli
          username: admin
          password: admin
          grant_type: password
        return_content: true
      until: sso_auth.status != -1
      retries: 10
      delay: 1
      register: sso_auth

    - name: Set KeyCloak access token
      set_fact:
        token: "{{ sso_auth.json.access_token }}"

    - name: Create KeyCloak client
      keycloak_client:
        auth_client_id: admin-cli
        auth_keycloak_url: "{{ svc_auth_baseurl }}/auth"
        auth_realm: "{{ auth_realm }}"
        auth_username: admin
        auth_password: admin
        client_id: webapp-ui
        protocol: openid-connect
        public_client: true
        root_url: "{{ webui_baseurl }}"
        redirect_uris:
          - "{{ webui_baseurl }}/*"
        direct_access_grants_enabled: true
        standard_flow_enabled: true
        client_authenticator_type: client-secret
        state: present
      register: client_register
  always:
    - name: Logout with KeyCloak
      uri:
        url: "{{ svc_auth_baseurl }}/auth/realms/{{ auth_realm }}\
          /protocol/openid-connect/logout"
        method: POST
        body_format: form-urlencoded
        body:
          client_id: admin-cli
          refresh_token: "{{ sso_auth.json.refresh_token }}"
        status_code: 204
      when: sso_auth.json is defined
...
