---
- hosts: all
  become: true
  connection: local

  vars:
    public_hostname: "{{ lookup('env', 'PUBLIC_HOSTNAME') or \
      ansible_eth1.ipv4.address \
      | lower }}"

    auth_realm: master
    auth_protocol: http
    auth_hostname: "{{ public_hostname }}"
    auth_baseurl: "{{ auth_protocol }}://\
      {{ auth_hostname }}\
      {% if auth_port is defined %}\
      :{{ auth_port }}\
      {% endif %}"

    svc_auth_protocol: http
    svc_auth_port: 8080
    svc_auth_hostname: localhost
    svc_auth_baseurl: "{{ svc_auth_protocol }}://\
      {{ svc_auth_hostname }}\
      {% if svc_auth_port is defined %}\
      :{{ svc_auth_port }}\
      {% endif %}"

    api_protocol: https
    api_baseurl: "{{ api_protocol }}://{{ public_hostname }}/api"

    admin_api_protocol: http
    admin_api_baseurl: "{{ admin_api_protocol }}://{{ public_hostname }}\
      {% if admin_api_port is defined %}\
      :{{ admin_api_port }}\
      {% endif %}/admin"

    svc_admin_api_protocol: http
    svc_admin_api_port: 8001
    svc_admin_api_hostname: localhost
    svc_admin_api_baseurl: "{{ svc_admin_api_protocol }}://{{ svc_admin_api_hostname }}\
      {% if svc_admin_api_port is defined %}\
      :{{ svc_admin_api_port }}\
      {% endif %}"

  tasks:
    - name: Execute resource setup tasks
      import_tasks: tasks/resources.yml
      tags:
        - kong
        - keycloak

    - name: Execute Kong setup tasks
      import_tasks: tasks/kong.yml
      tags:
        - kong

    - name: Execute KeyCloak setup tasks
      import_tasks: tasks/keycloak.yml
      tags:
        - keycloak

    - name: Execute kong endpoint setup tasks
      import_tasks: tasks/kong-endpoint.yml
      tags:
        - kong-endpoint
        - endpoint

    - name: Execute endpoint setup tasks
      import_tasks: tasks/keycloak-endpoint.yml
      tags:
        - keycloak-endpoint
        - endpoint
...
