---
- block:
    - name: Authenticate with KeyCloak
      uri:
        url: "http://localhost:8080/auth/realms/master\
          /protocol/openid-connect/token"
        method: POST
        body_format: form-urlencoded
        body:
          client_id: admin-cli
          username: admin
          password: admin
          grant_type: password
        return_content: yes
      until: sso_auth.status != -1
      retries: 10
      delay: 1
      register: sso_auth

    - name: Set KeyCloak access token
      set_fact:
        token: "{{ sso_auth.json.access_token }}"

    - name: Create KeyCloak test client
      keycloak_client:
        auth_client_id: admin-cli
        auth_keycloak_url: http://localhost:8080/auth
        auth_realm: master
        auth_username: admin
        auth_password: admin
        client_id: webapp-oapi
        protocol: openid-connect
        public_client: false
        root_url: http://localhost:3000
        redirect_uris:
          - http://localhost:3000/*
          - http://localhost:3000/docs/*
        standard_flow_enabled: true
        service_accounts_enabled: true
        authorization_services_enabled: true
        client_authenticator_type: client-secret
        state: present

    - name: Create KeyCloak client
      keycloak_client:
        auth_client_id: admin-cli
        auth_keycloak_url: http://localhost:8080/auth
        auth_realm: master
        auth_username: admin
        auth_password: admin
        client_id: webapp
        id: "{{ sid }}"
        protocol: openid-connect
        public_client: false
        root_url: http://localhost:8000/webapp
        redirect_uris:
          - http://localhost:8000/webapp/*
        standard_flow_enabled: true
        service_accounts_enabled: true
        authorization_services_enabled: true
        client_authenticator_type: client-secret
        state: present
      register: client_register

    - name: Retrieve client ID
      set_fact:
        cid: "{{ client_register.proposed.id }}"

    - name: Retrieve client secret
      uri:
        url: "http://localhost:8080/auth/admin/realms/master/clients\
          /{{ cid }}/client-secret"
        headers:
          Authorization: "bearer {{ token }}"
        return_content: yes
      register: client_secret

    - block:
        - name: Check if webapp is registered with keycloak
          uri:
            url: http://localhost:8001/services/webapp-service/plugins?name=oidc
            return_content: yes
          register: endpoint_configure
          failed_when: endpoint_configure.json.data == []
          no_log: True
      rescue:
        - name: Configure webapp with keycloak
          uri:
            url: http://localhost:8001/services/webapp-service/plugins
            method: POST
            body_format: json
            body:
              name: oidc
              config:
                client_id: webapp
                client_secret: "{{ client_secret.json.value }}"
                discovery: "http://{{ ansible_eth1.ipv4.address }}:\
                  8080/auth/realms/master/.well-known/openid-configuration"
            timeout: 300
            status_code: 201
            return_content: yes
          changed_when: true
          register: endpoint_configure

  always:
    - name: Logout with KeyCloak
      uri:
        url: "http://localhost:8080/auth/realms/master/protocol/openid-connect\
          /logout"
        method: POST
        body_format: form-urlencoded
        body:
          client_id: admin-cli
          refresh_token: "{{ sso_auth.json.refresh_token }}"
        status_code: 204
      when: sso_auth.json is defined
...
