---
- hosts: all
  become: true
  connection: local

  tasks:
    - name: Remove DMZ containers
      docker_container:
        name: "{{ item }}"
        state: absent
      loop:
        - nginx
      tags:
        - containers

    - name: Execute resource removal tasks
      import_tasks: tasks/resources.yml
      vars:
        sso_network_state: absent
        proxy_tls_state: absent
...
