---
- name: Verify OIDC plugin is loaded in Kong
  uri:
    url: http://localhost:8001
    return_content: yes
  register: plugin_register
  until: plugin_register.json.plugins.available_on_server.oidc|d(false)
  retries: 10

- block:
    - name: Check if mock service is loaded in Kong
      uri:
        url: http://localhost:8001/services/mock-service
      register: service_register
  rescue:
    - name: Add mock service to Kong
      uri:
        url: http://localhost:8001/services
        method: POST
        body_format: form-urlencoded
        body:
          name: mock-service
          url: http://mockbin.org/request
        return_content: yes
        status_code: 201
      register: service_register

- name: Retrieve mock service ID
  set_fact:
    sid: "{{ service_register.json.id }}"

- block:
    - name: Check if mock route is loaded in Kong
      uri:
        url: "http://localhost:8001/routes?service.id={{ sid }}"
      register: route_register
      failed_when: route_register.json.data == []
  rescue:
    - name: Register route in Kong
      uri:
        url: http://localhost:8001/routes
        method: POST
        body_format: form-urlencoded
        body:
          service.id: "{{ sid }}"
          paths[]: /mock
        return_content: yes
        status_code: 201
      register: route_register
...
