---
- name: Setup networks
  docker_network:
    name: "{{ item }}"
    state: "{{ sso_network_state | d('present') }}"
  loop:
    - api-net
    - kong-net
    - keycloak-net
  tags:
    - networks

- name: Setup volumes
  docker_volume:
    name: "{{ item }}"
    state: "{{ sso_volume_state | d('present') }}"
  loop:
    - kong-datastore
    - keycloak-datastore
  tags:
    - volumes
...
