FROM kong:1.5.0-centos

LABEL description="Centos 7 + Kong 1.5.0-centos + kong-oidc plugin"

ENV KONG_PLUGINS=oidc

RUN yum install -y git unzip \
  && yum clean all \
  && rm -rf /var/cache/yum \
  && luarocks install kong-oidc-auth
